services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/todo-app/todo-frontend
    ports:
      - 5173:5173
    container_name: todo-frontend-dev